### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by TummeliRuonakoski** [TummeliRuonakoski/norascoffeeshop-bc#2]
Needs to have:
- An email field
- A password field
- Login button
- Create an account link
- Forgotten password link
- Actual functionality

**Comment by s2100637** [comment]
Added simple form without the functionality

**Comment by TummeliRuonakoski** [comment]
Osastotiedot syötetään käsin tietokantaan. IDn tulee alkaa numerosta 1
